# --- Defaults ---

# --- pymarl options ---
runner: "episode"
mac: "basic_mac"
env: "sc2"
env_args: {}
batch_size_run: 1
training_iters: 1  # gradient steps per data collection (increase for parallel runner)
test_nepisode: 20
test_interval: 2000
test_greedy: True
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 10000
use_cuda: True
buffer_cpu_only: True

# --- Logging options ---
use_tensorboard: True
save_model: False
save_model_interval: 2000000
checkpoint_path: ""
evaluate: False
load_step: 0
save_replay: False
local_results_path: "results"

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32
buffer_size: 32
lr: 0.0005
optim_alpha: 0.99
optim_eps: 0.00001
grad_norm_clip: 10
target_update_interval: 200

# --- Agent parameters ---
agent: "rnn"
rnn_hidden_dim: 64
obs_agent_id: True
obs_last_action: True

# --- Action selector ---
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
seed: 12345
